### PR TITLE
crypto_wrapper: add support for blake2s

### PR DESCRIPTION
**Pull request by zx2c4**
Wait until DaGenix/rust-crypto#358 is merged before merging this.

### CODE REVIEW

**Comment by trevp** [comment]
Oh, great!  thanks for doing this.

**Comment by zx2c4** [comment]
Looks like DaGenix/rust-crypto#358 has been merged now, and you can safely one-click-merge this pull request.

**Comment by trevp** [comment]
Cool, do you agree with the terms from: https://github.com/trevp/screech/blob/master/LICENSE

?

**Comment by zx2c4** [comment]
Yes. I agree with the terms on https://github.com/trevp/screech/blob/master/LICENSE as of 'Thu Apr 21 03:03:54 CEST 2016'.

**Comment by zx2c4** [comment]
I hereby place the contents of this pull request into public domain.

**Pull request merged**
